### ISSUE TITLE
CLS Session: Nurturing Global Meetups

### ISSUE THREAD

**Issue by mjang** [CLSummit/CLS2018#4]
Nurturing Global Meetups

Intro -
Volunteers to take notes (e.g. GH Issue)
< 5 min intro -- plus several topics 
When I’m done, we’ll go around the table
Discuss potential topics, few min discuss each
Collective lessons learned to help us all

Self-Intro: Meetup lead Write the Docs. TW ForgeRock
Started as lone writer in office
Found community in WtD NA 2014

Found lots of others in similar situations
Started a Write the Docs Meetup here in PDX

 I came to CLS, and intro’d myself: “I started a Meetup”
Twitter: “I probably broke all the rules” (https://twitter.com/ScrapHacker/status/490601221497966592)
Energized by “community” of CLS
WTD 2015 -- HOWTO start a Meetup
Today -- 37 Meetups -- Now WtD Meetup Lead, 

Others here in a similar situation

Our community
Completed first conference calls
(Eastern and Western Hemispheres)
Slack-based community
Many meet at conferences
Docs on how to start meetups

Hope we can share best practices
If you organize meetups, can we stay in touch?

Topics

Promoting new Meetups
* Finding new members (increasing community engagement)
Helping organizers help each other
* Sharing meetup ideas
* Interactive workshops
What Makes a Great Meetup (Topics? interactive, social?)
Nurturing Diversity (affirmative action?)
More?

Few min on each topic, brainstorm

Publish

**Comment by resonantspectrum** [comment]
Sunday, July 15, 2018 Session 1 at 3:00 PM

18 attendees

Meetup.com is the central coordinatiing point. Someone is developing an open source project that does what Meetup does.

Idea for this session grew out of Write the Docs, now 37 meetups in 12 time zones.

Most meetups are face-to-face because you want to build interaction and community.

How do you find people to start a meetup? What makes a great meetup?

Ask for meetups as a GitHub issue. One organization created a forum for potential meetup organizers.

Meetup can be great for decentralizing. But some organizations try to maintain control, essentially saying they own the meetups. Others encourae individuals to start new meetups on their own. But don't have the independent meetups call themselves official. Empowerment within guidelines that help them do the job effectively.

Speaker directory that people can add themselves to. Specify their expertise, offer to mentor less experienced speakers.

Remote speakers are OK, may be easier on the budget.

Cross-polinization: your speaker can be on a related topic that's not directly your core topic.

Encourage small communities too, even if it's just around a coffee table.

Basic tasks: find a good location, some people require food, get good speakers, advertise to your community well. Many meetups are in a competitive environment. But most meetups start very small and can be informal at the beginning.

Meetup Pro is training organizers.
